#-Information---------------------------------------------------------------------------------------
name: pointfinder
version: 2.3.13
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: resistance
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    Finds chromosomal point mutations with the CGE pointfinder tool
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://stefanocardinale/pointfinder:2.3.13"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_resources/pointfinder_db/"
  adapters_fasta: "/bifrost_resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
   - qcquickie/contigs.fasta
  sample:
    properties:
      resistance:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      resistance:
  sample_component:
    summary:
    results:
      contigs_blastn_results.tsv: {}
#---------------------------------------------------------------------------------------------------