#-Information---------------------------------------------------------------------------------------
name: pointfinder
version: 1.0
target: sample
type: pipeline
recommendation: optional
description: >
  Uses pointfinder and blastn to detect point mutations that result in antimicrobial resistance. 
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
#assembly_with: "skesa"  # Choices: skesa|spades
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
#adapters_fasta: "resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
#this requirement looks for the specific sample component with name 'assemblatron' and the key 'status' 
#checking the provided value
  component: 
    assemblatron:
      status: Success
  #this requirement looks directly at the sample object 'reads' dictionary at R1 and R2 keys.
  #It only checks whether there are there (initialized), it doesn't care about their value
  sample:
    reads:
      R1:
      R2:
    properties:
      provided_species: ['Escherichia coli', 'Salmonella enterica']
#-DB Value changes (excluding component output)-----------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------
