#-Information---------------------------------------------------------------------------------------
name: pointfinder
version: 2.2
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: resistance
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    Finds chromosomal point mutations with the CGE pointfinder tool
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://stefanocardinale/pointfinder:2.1"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_resources/pointfinder_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
#this requirement looks for the specific sample component with name 'assemblatron' and the key 'status' 
#checking the provided value
  component: 
    qcquickie:
      status: Success
  #this requirement looks directly at the sample object 'reads' dictionary at R1 and R2 keys.
  #It only checks whether there are there (initialized), it doesn't care about their value
  sample:
    properties:
      provided_species: ['Escherichia coli', 'Salmonella enterica','Campylobacter jejuni']
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
  sample:
    properties:
      resistance:
        summary: 
        component:
          _id: 
          date: "ObjectId"
    report:
      resistance:
        title: Resistance
        info: *dockerfile
        columns:  # headers, these values are statically present in datadump
          - {id: "Residue", name: "Amino acid change"}
          - {id: "Mutation", name: "Mutation"}
          - {id: "Nucleotide", name: "Nucleotide change"}
          - {id: "PMID", name: "PMID"}
          - {id: "Resistance", name: "Resistance"}
        data: []  # list of dicts parsed in datadump
  sample_component:
    summary:
    results:
#---------------------------------------------------------------------------------------------------
